In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-4.7577e+03,  4.5577e-41, -4.7577e+03],
        [ 4.5577e-41,  5.0017e-40,  1.7779e-37],
        [ 2.5353e+30,  8.4078e-45,  1.2359e-42],
        [ 1.1429e-39,  1.1652e-32,  2.5353e+30],
        [ 1.4013e-44,  3.7471e-42,  1.0511e-39]])


In [3]:
#Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.7175, 0.0609, 0.7987],
        [0.9683, 0.5847, 0.6796],
        [0.1031, 0.3219, 0.1598],
        [0.2268, 0.8478, 0.0033],
        [0.5331, 0.2186, 0.5032]])


In [4]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5673, -0.4282,  0.4005],
        [-0.3199,  2.1170,  0.2216],
        [-0.7849,  0.0880, -0.6344],
        [ 0.2431,  0.4537, -1.9770],
        [-0.1059,  0.2044,  1.0104]])


In [7]:
print(x.size())


torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3825,  0.5502,  1.1708],
        [-0.2036,  2.3637,  0.8463],
        [-0.6580,  0.5657, -0.4463],
        [ 1.0154,  1.2140, -1.0465],
        [-0.0514,  0.3607,  1.2502]])


In [9]:
print(torch.add(x, y))


tensor([[ 0.3825,  0.5502,  1.1708],
        [-0.2036,  2.3637,  0.8463],
        [-0.6580,  0.5657, -0.4463],
        [ 1.0154,  1.2140, -1.0465],
        [-0.0514,  0.3607,  1.2502]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3825,  0.5502,  1.1708],
        [-0.2036,  2.3637,  0.8463],
        [-0.6580,  0.5657, -0.4463],
        [ 1.0154,  1.2140, -1.0465],
        [-0.0514,  0.3607,  1.2502]])


In [11]:
# adds x to y
y.add_(x)
print(y)
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), will change x.

tensor([[ 0.3825,  0.5502,  1.1708],
        [-0.2036,  2.3637,  0.8463],
        [-0.6580,  0.5657, -0.4463],
        [ 1.0154,  1.2140, -1.0465],
        [-0.0514,  0.3607,  1.2502]])


In [12]:
print(x[:, 1])


tensor([-0.4282,  2.1170,  0.0880,  0.4537,  0.2044])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4461])
0.4460687041282654


# NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

## Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
# See how the numpy array changed in value.

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [19]:
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.4461], device='cuda:0')
tensor([1.4461], dtype=torch.float64)
